#nullable enable

// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotNetSourceGeneratorToolkit.Generators;

/// <summary>
/// A real Roslyn incremental generator that emits boilerplate <c>ToString()</c> and value
/// equality members for partial classes annotated with <c>[GenerateToString]</c> or
/// <c>[GenerateEquals]</c>.
/// </summary>
/// <remarks>
/// Unlike the template based generator services in this toolkit, this generator plugs directly
/// into the compiler via <see cref="IIncrementalGenerator"/>. It is intentionally small and
/// self contained so its output can be asserted exactly by snapshot tests and its diagnostics
/// verified by ID and severity.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class AutoImplementGenerator : IIncrementalGenerator
{
    /// <summary>Fully qualified metadata name of the ToString marker attribute.</summary>
    public const string ToStringAttributeName = "DotNetSourceGeneratorToolkit.Generated.GenerateToStringAttribute";

    /// <summary>Fully qualified metadata name of the equality marker attribute.</summary>
    public const string EqualsAttributeName = "DotNetSourceGeneratorToolkit.Generated.GenerateEqualsAttribute";

    /// <summary>Reported when a marker attribute is applied to a non-partial type.</summary>
    public static readonly DiagnosticDescriptor MustBePartial = new(
        id: "SGTK001",
        title: "Auto-implemented type must be partial",
        messageFormat: "Type '{0}' is annotated with an auto-implement attribute but is not declared 'partial'",
        category: "DotNetSourceGeneratorToolkit.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Reported when a marker attribute is applied to a type that has no eligible members.</summary>
    public static readonly DiagnosticDescriptor NoEligibleMembers = new(
        id: "SGTK002",
        title: "Auto-implemented type has no public instance properties",
        messageFormat: "Type '{0}' has no public instance properties, so the generated member is trivial",
        category: "DotNetSourceGeneratorToolkit.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <summary>Reported when a marker attribute is applied to a static type.</summary>
    public static readonly DiagnosticDescriptor MustNotBeStatic = new(
        id: "SGTK003",
        title: "Auto-implemented type must not be static",
        messageFormat: "Type '{0}' is static and cannot have instance members generated",
        category: "DotNetSourceGeneratorToolkit.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace DotNetSourceGeneratorToolkit.Generated
        {
            /// <summary>Marks a partial class for automatic ToString() generation.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class GenerateToStringAttribute : global::System.Attribute
            {
            }

            /// <summary>Marks a partial class for automatic value-equality generation.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class GenerateEqualsAttribute : global::System.Attribute
            {
            }
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("AutoImplementAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var toStringTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
                ToStringAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => Target.From(ctx, TargetKind.ToString))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        var equalsTargets = context.SyntaxProvider.ForAttributeWithMetadataName(
                EqualsAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => Target.From(ctx, TargetKind.Equals))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(toStringTargets, static (spc, target) => Emit(spc, target));
        context.RegisterSourceOutput(equalsTargets, static (spc, target) => Emit(spc, target));
    }

    private static void Emit(SourceProductionContext context, Target target)
    {
        foreach (var diagnostic in target.Diagnostics)
            context.ReportDiagnostic(diagnostic.ToDiagnostic());

        if (!target.CanGenerate)
            return;

        var source = target.Kind == TargetKind.ToString
            ? BuildToString(target)
            : BuildEquals(target);

        var hint = $"{target.QualifiedHint}.{target.Kind}.g.cs";
        context.AddSource(hint, SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildToString(Target target)
    {
        var sb = new IndentedWriter();
        WriteHeader(sb, target);

        var body = target.Properties.Count == 0
            ? $"\"{target.TypeName} {{ }}\""
            : "$\"" + target.TypeName + " {{ " +
              string.Join(", ", target.Properties.Select(p => $"{p} = {{{p}}}")) +
              " }}\"";

        sb.Line("/// <inheritdoc />");
        sb.Line($"public override string ToString() => {body};");

        WriteFooter(sb, target);
        return sb.ToString();
    }

    private static string BuildEquals(Target target)
    {
        var sb = new IndentedWriter();
        WriteHeader(sb, target, extraInterface: $"global::System.IEquatable<{target.TypeName}>");

        var comparisons = target.Properties.Count == 0
            ? "true"
            : string.Join(Environment.NewLine + "            && ",
                target.Properties.Select(p =>
                    $"global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(this.{p}, other.{p})"));

        sb.Line("/// <inheritdoc />");
        sb.Line($"public bool Equals({target.TypeName}? other)");
        sb.Line("{");
        sb.Indent();
        sb.Line("if (other is null) return false;");
        sb.Line("if (global::System.Object.ReferenceEquals(this, other)) return true;");
        sb.Line($"return {comparisons};");
        sb.Outdent();
        sb.Line("}");
        sb.Blank();
        sb.Line("/// <inheritdoc />");
        sb.Line($"public override bool Equals(object? obj) => Equals(obj as {target.TypeName});");
        sb.Blank();
        sb.Line("/// <inheritdoc />");
        sb.Line("public override int GetHashCode()");
        sb.Line("{");
        sb.Indent();
        sb.Line("var hash = new global::System.HashCode();");
        foreach (var p in target.Properties)
            sb.Line($"hash.Add(this.{p});");
        sb.Line("return hash.ToHashCode();");
        sb.Outdent();
        sb.Line("}");

        WriteFooter(sb, target);
        return sb.ToString();
    }

    private static void WriteHeader(IndentedWriter sb, Target target, string? extraInterface = null)
    {
        sb.Line("// <auto-generated/>");
        sb.Line("#nullable enable");
        var hasNamespace = !string.IsNullOrEmpty(target.Namespace);
        if (hasNamespace)
        {
            sb.Line($"namespace {target.Namespace}");
            sb.Line("{");
            sb.Indent();
        }

        var declaration = $"partial class {target.TypeName}";
        if (extraInterface is not null)
            declaration += $" : {extraInterface}";

        sb.Line(declaration);
        sb.Line("{");
        sb.Indent();
    }

    private static void WriteFooter(IndentedWriter sb, Target target)
    {
        sb.Outdent();
        sb.Line("}");
        if (!string.IsNullOrEmpty(target.Namespace))
        {
            sb.Outdent();
            sb.Line("}");
        }
    }

    private enum TargetKind
    {
        ToString,
        Equals,
    }

    /// <summary>Serializable diagnostic payload kept equatable so caching is not defeated.</summary>
    private readonly record struct DiagnosticInfo(string Id, Location Location, string TypeName)
    {
        public Diagnostic ToDiagnostic()
        {
            var descriptor = Id switch
            {
                "SGTK001" => MustBePartial,
                "SGTK002" => NoEligibleMembers,
                "SGTK003" => MustNotBeStatic,
                _ => throw new InvalidOperationException($"Unknown diagnostic id: {Id}"),
            };
            return Diagnostic.Create(descriptor, Location, TypeName);
        }
    }

    private sealed record Target(
        TargetKind Kind,
        string? Namespace,
        string TypeName,
        EquatableArray<string> Properties,
        EquatableArray<DiagnosticInfo> Diagnostics,
        bool CanGenerate)
    {
        public string QualifiedHint =>
            string.IsNullOrEmpty(Namespace) ? TypeName : $"{Namespace}.{TypeName}";

        public static Target? From(GeneratorAttributeSyntaxContext context, TargetKind kind)
        {
            if (context.TargetSymbol is not INamedTypeSymbol symbol)
                return null;

            var declaration = (ClassDeclarationSyntax)context.TargetNode;
            var location = declaration.Identifier.GetLocation();
            var diagnostics = new List<DiagnosticInfo>();

            var isPartial = declaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
            if (!isPartial)
                diagnostics.Add(new DiagnosticInfo("SGTK001", location, symbol.Name));

            if (symbol.IsStatic)
                diagnostics.Add(new DiagnosticInfo("SGTK003", location, symbol.Name));

            var properties = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public
                            && !p.IsStatic
                            && !p.IsIndexer
                            && p.GetMethod is not null)
                .Select(p => p.Name)
                .ToImmutableArray();

            if (properties.Length == 0)
                diagnostics.Add(new DiagnosticInfo("SGTK002", location, symbol.Name));

            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var canGenerate = isPartial && !symbol.IsStatic;

            return new Target(
                kind,
                ns,
                symbol.Name,
                new EquatableArray<string>(properties),
                new EquatableArray<DiagnosticInfo>(diagnostics.ToImmutableArray()),
                canGenerate);
        }
    }
}
