// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using DotNetSourceGeneratorToolkit.Domain;

namespace DotNetSourceGeneratorToolkit.Examples;

/// Basic example demonstrating repository, mapper, and validator generation
public class BasicExample
{
    // Define domain entities with generation attributes
    [Repository]
    [Mapper]
    [Validator]
    public class User
    {
        public int Id { get; set; }
        public string Email { get; set; } = string.Empty;
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public bool IsActive { get; set; } = true;
    }

    // DTO for API responses
    [Mapper]
    public class UserDto
    {
        public int Id { get; set; }
        public string Email { get; set; } = string.Empty;
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
    }

    // Usage example
    public class UserService
    {
        // These would be generated by the toolkit:
        // - IUserRepository: repository interface
        // - UserRepository: concrete repository
        // - IUserMapper: mapping interface
        // - UserMapper: concrete mapper
        // - IUserValidator: validator interface
        // - UserValidator: concrete validator

        public async Task<UserDto?> GetUserAsync(
            int userId,
            IUserRepository repository,
            IUserMapper mapper,
            IUserValidator validator)
        {
            // Fetch from repository (generated)
            var user = await repository.GetByIdAsync(userId);
            if (user == null)
                return null;

            // Validate before returning (generated)
            var validationResult = await validator.ValidateAsync(user);
            if (!validationResult.IsValid)
                throw new InvalidOperationException("User validation failed");

            // Map to DTO (generated)
            return mapper.MapToDto(user);
        }

        public async Task<User> CreateUserAsync(
            UserDto dto,
            IUserRepository repository,
            IUserMapper mapper,
            IUserValidator validator)
        {
            // Map from DTO (generated)
            var user = mapper.MapFromDto(dto);

            // Validate before creating (generated)
            var validationResult = await validator.ValidateAsync(user);
            if (!validationResult.IsValid)
                throw new InvalidOperationException("User validation failed");

            // Create in repository (generated)
            return await repository.CreateAsync(user);
        }
    }
}
