#nullable enable

// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using DotNetSourceGeneratorToolkit.Generators;
using FluentAssertions;
using Xunit;

namespace DotNetSourceGeneratorToolkit.Tests.Generators;

/// <summary>
/// Snapshot tests that assert the exact source emitted by <see cref="AutoImplementGenerator"/>.
/// Any change to the generated text is a deliberate decision and must update these expectations.
/// </summary>
public sealed class AutoImplementGeneratorSnapshotTests
{
    private const string ProductSource = """
        using DotNetSourceGeneratorToolkit.Generated;
        namespace Shop.Domain
        {
            [GenerateToString]
            [GenerateEquals]
            public partial class Product
            {
                public int Id { get; set; }
                public string Name { get; set; }
                public decimal Price { get; set; }
            }
        }
        """;

    [Fact]
    public void PostInitialization_EmitsMarkerAttributes()
    {
        var result = GeneratorTestHarness.Run(new AutoImplementGenerator(), ProductSource);

        var attributes = GeneratorTestHarness.GetGeneratedText(result, "AutoImplementAttributes.g.cs");

        attributes.Should().Be(GeneratorTestHarness.Normalize("""
            // <auto-generated/>
            #nullable enable
            namespace DotNetSourceGeneratorToolkit.Generated
            {
                /// <summary>Marks a partial class for automatic ToString() generation.</summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed class GenerateToStringAttribute : global::System.Attribute
                {
                }

                /// <summary>Marks a partial class for automatic value-equality generation.</summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed class GenerateEqualsAttribute : global::System.Attribute
                {
                }
            }
            """));
    }

    [Fact]
    public void GenerateToString_ProducesExactSource()
    {
        var result = GeneratorTestHarness.Run(new AutoImplementGenerator(), ProductSource);

        var generated = GeneratorTestHarness.GetGeneratedText(result, "Product.ToString.g.cs");

        generated.Should().Be(GeneratorTestHarness.Normalize("""
            // <auto-generated/>
            #nullable enable
            namespace Shop.Domain
            {
                partial class Product
                {
                    /// <inheritdoc />
                    public override string ToString() => $"Product {{ Id = {Id}, Name = {Name}, Price = {Price} }}";
                }
            }
            """));
    }

    [Fact]
    public void GenerateEquals_ProducesExactSource()
    {
        var result = GeneratorTestHarness.Run(new AutoImplementGenerator(), ProductSource);

        var generated = GeneratorTestHarness.GetGeneratedText(result, "Product.Equals.g.cs");

        generated.Should().Be(GeneratorTestHarness.Normalize("""
            // <auto-generated/>
            #nullable enable
            namespace Shop.Domain
            {
                partial class Product : global::System.IEquatable<Product>
                {
                    /// <inheritdoc />
                    public bool Equals(Product? other)
                    {
                        if (other is null) return false;
                        if (global::System.Object.ReferenceEquals(this, other)) return true;
                        return global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(this.Id, other.Id)
                        && global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(this.Name, other.Name)
                        && global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(this.Price, other.Price);
                    }

                    /// <inheritdoc />
                    public override bool Equals(object? obj) => Equals(obj as Product);

                    /// <inheritdoc />
                    public override int GetHashCode()
                    {
                        var hash = new global::System.HashCode();
                        hash.Add(this.Id);
                        hash.Add(this.Name);
                        hash.Add(this.Price);
                        return hash.ToHashCode();
                    }
                }
            }
            """));
    }

    [Fact]
    public void GenerateToString_ForGlobalNamespaceType_OmitsNamespaceBlock()
    {
        const string source = """
            using DotNetSourceGeneratorToolkit.Generated;
            [GenerateToString]
            public partial class Ticket
            {
                public string Code { get; set; }
            }
            """;

        var result = GeneratorTestHarness.Run(new AutoImplementGenerator(), source);
        var generated = GeneratorTestHarness.GetGeneratedText(result, "Ticket.ToString.g.cs");

        generated.Should().Be(GeneratorTestHarness.Normalize("""
            // <auto-generated/>
            #nullable enable
            partial class Ticket
            {
                /// <inheritdoc />
                public override string ToString() => $"Ticket {{ Code = {Code} }}";
            }
            """));
    }

    [Fact]
    public void OnlyPublicInstanceProperties_AreIncluded()
    {
        const string source = """
            using DotNetSourceGeneratorToolkit.Generated;
            namespace Acme
            {
                [GenerateToString]
                public partial class Account
                {
                    public string Owner { get; set; }
                    private int Secret { get; set; }
                    public static int Count { get; set; }
                    public int WriteOnly { set { } }
                }
            }
            """;

        var result = GeneratorTestHarness.Run(new AutoImplementGenerator(), source);
        var generated = GeneratorTestHarness.GetGeneratedText(result, "Account.ToString.g.cs");

        generated.Should().Contain("Owner = {Owner}");
        generated.Should().NotContain("Secret");
        generated.Should().NotContain("Count");
        generated.Should().NotContain("WriteOnly");
    }
}
